#Sample username for !autofill

sample_usernames = [
    "cool_cat42",
    "meme_lord_2000",
    "dancing_banana",
    "coffee_addict_87",
    "ninja_coder",
    "sunset_chaser",
    "pizza_lover_3000",
    "gamer_girl_xx",
    "bookworm_123",
    "fitness_freak_2024",
    "travel_bug_nomad",
    "music_maestro",
    "tech_guru_101",
    "food_photographer",
    "eco_warrior_green",
    "movie_buff_cinephile",
    "art_vandal",
    "crypto_king_btc",
    "yoga_master_zen",
    "fashionista_chic",
    "dog_whisperer_woof",
    "meme_queen_lol",
    "sports_fanatic_23",
    "science_nerd_42",
    "history_buff_1776",
    "conspiracy_theorist_x",
    "dank_memer_420",
    "cosmic_explorer",
    "plant_parent_green_thumb",
    "social_butterfly_xoxo"
]