from ttv_battleroyale.battleroyale_logic import Weapon, Event

#Sample set of weapons and events generated by ChatGPT4 and Free plan account.
#These could serve for testing purposes or as an inspiration for custom streamer sets

sample_usernames = [
    "cool_cat42",
    "meme_lord_2000",
    "dancing_banana",
    "coffee_addict_87",
    "ninja_coder",
    "sunset_chaser",
    "pizza_lover_3000",
    "gamer_girl_xx",
    "bookworm_123",
    "fitness_freak_2024",
    "travel_bug_nomad",
    "music_maestro",
    "tech_guru_101",
    "food_photographer",
    "eco_warrior_green",
    "movie_buff_cinephile",
    "art_vandal",
    "crypto_king_btc",
    "yoga_master_zen",
    "fashionista_chic",
    "dog_whisperer_woof",
    "meme_queen_lol",
    "sports_fanatic_23",
    "science_nerd_42",
    "history_buff_1776",
    "conspiracy_theorist_x",
    "dank_memer_420",
    "cosmic_explorer",
    "plant_parent_green_thumb",
    "social_butterfly_xoxo"
]

sample_weapons = [
    # Melee Weapons
    Weapon("Rusty Dagger", 6),               # d6
    Weapon("Steel Longsword", 8),            # d8
    Weapon("Warhammer of Fury", 10),         # d10
    Weapon("Battle Axe of the Fallen", 10),  # d10
    Weapon("Gladiator’s Gladius", 8),        # d8
    Weapon("Twin Daggers of the Assassin", 6), # d6
    Weapon("Titan’s Greatsword", 12),        # d12
    Weapon("Mace of the Holy Light", 10),    # d10
    Weapon("Bloodthirster Axe", 12),         # d12
    Weapon("Doombringer Scythe", 20),        # d20

    # Ranged Weapons
    Weapon("Hunter’s Bow", 6),               # d6
    Weapon("Crossbow of Precision", 8),      # d8
    Weapon("Elven Longbow", 10),             # d10
    Weapon("Repeating Crossbow", 8),         # d8
    Weapon("Sniper Rifle of the Eagle", 12), # d12
    Weapon("Hand Cannon", 10),               # d10
    Weapon("Stormbringer Bow", 12),          # d12
    Weapon("Lightning Javelin", 10),         # d10
    Weapon("Dragonbreath Pistol", 12),       # d12
    Weapon("Orbital Strike Device", 20),     # d20

    # Magic Weapons
    Weapon("Fireball Spell", 8),             # d8
    Weapon("Ice Shard Spell", 6),            # d6
    Weapon("Arcane Blast", 10),              # d10
    Weapon("Lightning Bolt", 12),            # d12
    Weapon("Meteor Shower", 20),             # d20
    Weapon("Dark Matter", 12),               # d12
    Weapon("Inferno", 10),                   # d10
    Weapon("Chain Lightning", 8),            # d8
    Weapon("Soul Drain", 6),                 # d6
    Weapon("Summon Elemental", 12),          # d12

    # Hybrid Weapons
    Weapon("Flaming Sword", 10),             # d10
    Weapon("Frostmourne", 12),               # d12
    Weapon("Venomous Dagger", 8),            # d8
    Weapon("Thunder Hammer", 10),            # d10
    Weapon("Shadow Blade", 12),              # d12
    Weapon("Sunforged Spear", 10),           # d10
    Weapon("Lunar Scepter", 8),              # d8
    Weapon("Void Staff", 12),                # d12
    Weapon("Phoenix Feather Wand", 10),      # d10
    Weapon("Ethereal Bow", 12),              # d12
    Weapon("Cosmic Scythe", 20)              # d20
]

sample_events = [
    Event("Blessing of the Ancients", 5, [
        "{} has been blessed by the Ancients! Their attacks are now more powerful.",
        "The Ancients smile upon {}. Their strength grows immensely!"
    ]),
    Event("Curse of the Fallen", -3, [
        "{} has been cursed by the fallen spirits. Their strength diminishes.",
        "The shadows of the fallen weigh heavy on {}. Their attacks are weakened."
    ]),
    Event("Fury of the Storm", 4, [
        "The storm rages within {}. Their next strike will be ferocious!",
        "{} channels the fury of the storm, ready to unleash devastation!"
    ]),
    Event("Betrayal of a Friend", -2, [
        "{} feels the sting of betrayal. Their resolve falters.",
        "A friend’s betrayal leaves {} vulnerable, weakening their resolve."
    ]),
    Event("Blessing of Speed", 3, [
        "{} feels light as a feather, their attacks come swift and true.",
        "The winds favor {}, granting them unmatched speed in combat."
    ]),
    Event("Fatigue", -4, [
        "{} is overcome by fatigue, their movements slow down.",
        "Exhaustion takes its toll on {}. They struggle to keep up."
    ]),
    Event("Divine Protection", 6, [
        "A divine force shields {} from harm, boosting their confidence!",
        "{} is surrounded by a radiant aura, bolstering their defenses."
    ]),
    Event("Poisoned Blade", -3, [
        "{} has been poisoned! Their attacks are less effective.",
        "A toxic venom courses through {}, weakening their strikes."
    ]),
    Event("Rage of the Berserker", 5, [
        "{} is consumed by berserker rage! Their next attack will be devastating!",
        "The fury of a berserker fills {}. They’re ready to wreak havoc!"
    ]),
    Event("Misfire", -2, [
        "{} fumbles with their weapon, losing precious momentum.",
        "A critical misfire leaves {} vulnerable and off balance."
    ]),
    Event("Gift of the Elements", 4, [
        "The elements themselves empower {}. Their attacks burn with energy!",
        "{} harnesses the power of the elements, striking with greater force!"
    ]),
    Event("Haunted by Ghosts", -3, [
        "Spirits of the past haunt {}, sapping their strength.",
        "{} is tormented by restless spirits, weakening their resolve."
    ]),
    Event("Warrior's Spirit", 4, [
        "{} calls upon the warrior’s spirit, their attacks become relentless!",
        "The spirit of a fallen warrior guides {}’s hand, making their strikes more deadly!"
    ]),
    Event("Echoes of Doubt", -2, [
        "Doubt creeps into {}, shaking their confidence.",
        "The echoes of past failures weigh on {}, weakening their resolve."
    ]),
    Event("Phoenix's Rebirth", 5, [
        "{} rises from the ashes, their strength renewed!",
        "Like a phoenix, {} is reborn, ready to unleash renewed fury!"
    ]),
    Event("Sapped by Fear", -3, [
        "Fear grips {}, sapping their strength.",
        "{} is paralyzed by fear, making their attacks feeble."
    ]),
    Event("Blessing of Endurance", 4, [
        "{} gains the endurance of a mountain, able to withstand any blow!",
        "Endurance flows through {}, making them nearly unstoppable."
    ]),
    Event("Shadow of Death", -4, [
        "{} feels the cold grip of death, weakening their spirit.",
        "Death’s shadow looms over {}, draining their vitality."
    ]),
    Event("Fortune's Favor", 5, [
        "Fortune smiles upon {}, boosting their morale and power!",
        "{} is favored by fortune, making their attacks more effective."
    ]),
    Event("Plagued by Nightmares", -3, [
        "Nightmares plague {}, causing them to falter in combat.",
        "{} is haunted by terrifying visions, weakening their resolve."
    ])
]